name: dashboard_app
description: "Trading Dashboard Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_sign_in: ^6.1.6
  flutter_secure_storage: ^9.0.0
  file_picker: ^8.0.0+1
  dio: ^5.3.2
  fl_chart: ^0.68.0
  go_router: ^14.1.1
  diacritic: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

