name: Deploy Frontend (Flutter Web)
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

concurrency:
  group: deploy-frontend
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter info + enable web
        run: |
          flutter --version
          flutter config --enable-web
          flutter doctor -v

      - name: Build (Flutter Web)
        run: |
          flutter clean
          # Sem --web-renderer para evitar o erro; o Flutter escolhe o melhor para release
          flutter build web --release \
            --dart-define=API_BASE_URL=/api

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.SSH_PORT || 22 }}" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avzr --delete \
            -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT || 22 }}" \
            build/web/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/pinacle.com.br/
