name: Deploy Frontend (Flutter Web)
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

concurrency:
  group: deploy-frontend
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build (Flutter Web)
        run: |
          flutter clean
          flutter build web --release --web-renderer canvaskit \
            --dart-define=API_BASE_URL=/api

      # Prepara a chave SSH a partir do Secret e adiciona o host na known_hosts
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.SSH_PORT || 22 }}" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      # Faz o deploy com rsync nativo
      - name: Deploy with rsync
        run: |
          rsync -avzr --delete \
            -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT || 22 }}" \
            build/web/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/pinacle.com.br/
